### ISSUE TITLE
Hide alert for specific elements

### ISSUE THREAD

**Issue by arindammitra06** [rikschennink/short-and-sweet#1]
Hi,

First of all, Thank You for the wonderful library. I am planning to use the same in my project. But I wish I could hide/not show the counter for some specific elements which have maxlength attribute. 

I am initializing using shortAndSweet('textarea, input'). Is there any data-attribute for not showing the counter.

Thanks in advance.

**Comment by rikschennink** [comment]
You can use a class `shortAndSweet('.sands')` and then add the `sands` class to elements you want to add the component to

**Comment by arindammitra06** [comment]
Thank You. Let me try that and get back to you.

**Comment by arindammitra06** [comment]
Fantastic. Works just fine. I had one more question, sorry to bother you. Is there any way we can pass the maxlength count to a textarea, actually I am using an old version of struts which doesn't support maxlength (html:textarea) and hence the counter doesn't show for elements without maxlength.

**Comment by rikschennink** [comment]
Hi that is independent from the library, so can’t help with that, a million ways to do it.
